### ISSUE TITLE
Found an Error With Manual Override

### ISSUE THREAD

**Issue by XxSuPeRxX818** [mbudnek/hubitat-fan-thermostat#7]
Set manual override does not work at all. No matter what value you input. Also, override does not return to inactive after default override time has expired. Getting the following error in the logs:

groovy.lang.MissingMethodException: No signature of method: user_driver_mbudnek_Fan_Thermostat_481.runIn() is applicable for argument types: (java.math.BigDecimal, java.lang.String) values: [1, clearManualOverride]
Possible solutions: run(), run(), run(java.io.File, [Ljava.lang.String;), println(), auto(), on() on line 121 (setManualOverride)

**Comment by mbudnek** [comment]
Thanks for the report.  This should be fixed by #8.

There were two bugs causing these issues:
1. The device was attempting to read the default manual override time from settings instead of its device attribute
2. The manually specified time is passed as a `BigDecimal`, but Hubitat's `runIn` method wants a `Long`

Automatic manual override was working for me.  Probably because my device still had its default manual override setting from earlier in development when that was specified as a device setting.  Manually specifying a manual override time was just broken.
